### ISSUE TITLE
Style rule 14.

### ISSUE THREAD

**Issue by bjornj12** [avohq/reasonml-code-style-guide#2]
`14. ALWAYS use Js.Array2 and Js.String2. NEVER use Js.Array and Js.String. This is required to keep the => piping consistent.`

What are you using JS.array and Js.String for so much that it requires this rule? 
And when you say `the => piping consistent`, can you give an example?

Would it make sense to just create an extention file of Js to avoid this?

```
include Js;

module Array = Array2;
module String = String2; 
```

Something in that direction?

nice Style guide! 💯

**Comment by aleks-tpom6oh** [comment]
Hi Bjorn, thanks for your interest!

We are rarely using Js.String and that's the problem, it's hard to always keep in mind the thing that's rarely used

For example it's very easy to make an error like this, writing 
`property.type_->Js.String.replace("string", "str")`
instead of 
`property.type_->Js.String2.replace("string", "str")`
🤷‍♂️

I think there is a typo in the quote you mention, it should be `the -> piping consistent`

And your suggested setup looks very nice, thanks again!

**Comment by aleks-tpom6oh** [comment]
This issue is now referenced in the guide as a way to handle the 14 🎉
